Revert "[flang] Consider bind(c) when lowering calls to intrinsic module procedures (#70386)"
This reverts commit 529aeaff4d07857027c54e82c0c1ebb6cc6f63ac.

This change causes an error:
flang-new -fopenmp flang/test/Lower/OpenMP/omp-lib-num-threads.f90
error: loc("flang/test/Lower/OpenMP/omp-lib-num-threads.f90":13:3):
    flang/lib/Optimizer/Builder/IntrinsicCall.cpp:1375: not yet implemented: intrinsic: omp_set_num_threads